### PR TITLE
Upgrade to newer dependencies and toolchain

### PR DESCRIPTION
**Pull request by cmichi**
@pmikolajczyk41 or @deuszx Would it be possible to merge this today and publish a new release? That would be great!

### CODE REVIEW

**Review by deuszx — DISMISSED** [review]
Looks fairly straightforward to me. Let's wait for @pmikolajczyk41 for final review.

**EDIT**
Sorry, didn't notice CI is not passing. Let's make sure everything's green first.

**Comment by cmichi** [comment]
@deuszx Argh, I had run clippy locally, but apparently with different flags. I'll fix it.

**Comment by deuszx** [comment]
@cmichi One more thing – I know that CHANGELOG.md became a bit outdated but I think this particular release is more important than other so please add the entry there.

**Comment by cmichi** [comment]
@deuszx Done! Could you re-approve the CI run?

**Review by pmikolajczyk41 — APPROVED** [review]

**Comment by pmikolajczyk41** [comment]
@cmichi new version has been just published

**Comment by cmichi** [comment]
@pmikolajczyk41 @deuszx Great! And thanks for the super quick handling of this PR!

**Pull request merged**
